### PR TITLE
[#49] Support for temporal predicates

### PR DESCRIPTION
**Pull request by lc0197**
(new pull request, forgot to rebase in the previous one...) 
### Background
GDL extension for support of TPGM graphs as defined by [Rost et al.](https://dbs.uni-leipzig.de/de/publication/title/temporal_graph_analysis_using_gradoop). Here, valid and transaction intervals are defined for every graph element.

###### From/To Selectors
Every graph element (vertex/edge) is associated with 2 intervals, transaction (tx) and valid (val) interval.
Each interval is defined by its start (from) and end (to) timestamp.

For a graph element with variable name `a`, these four timestamps can be accessed in a property selector-like syntax:
* `a.tx_from`
* `a.tx_to`
* `a.val_from`
* `a.val_to`

Furthermore, the "global" transaction and valid interval are defined as the intersections of all elements' transaction/valid intervals. Their from and to stamps can be accessed by omitting the variable name:
* `tx_from`
* `tx_to`
* `val_from`
* `val_to`

###### Literals
Timestamp literals can be created in the following formats:
* `YYYY-MM-DDTHH:MM:SS` where `T` stands for the literal `T`
* `YYYY-MM-DD` (time is set to 00:00:00)
* `Now` (current timestamp)

###### Min/Max
Two types of "complex" timestamps can be created from a set of simple ones (selectors and literals):
* `MIN(t1,t2,...,tn)`
* `MAX(t1,t2,...,tn)`

Note that they can not be nested further, only selectors and literals are valid arguments for `MIN` and `MAX`.

###### Simple Comparisons
Timestamps can be compared using the usual comparators `<`, `<=`, `=`, `!=`, `>=`, and `>`
###### Syntactic Sugar
* `t1.before(t2)`: equal to `t1 < t2`
* `t1.after(t2)`: equal to `t1 > t2`

###### Selectors for Transaction/Valid Intervals
For a graph element with variable name `a`, the two intervals can be accessed in a property selector-like syntax:
* `a.tx`
* `a.val`

Furthermore, the "global" transaction and valid interval are defined as the intersections of all elements' transaction/valid intervals. These intervals can be accessed by omitting the variable name:
* `tx`
* `val`

###### Interval Literals
Custom intervals can be created from two timestamps denoting start and end of the interval: 
* `Interval(t1,t2)` where `t1` and `t2` are timestamps 

When such a interval is created, a constraint `t1 <= t2` is implicitly added.
###### Merge
Two intervals can be merged, i.e. intersected. This yields a new interval. The merge operation is only defined, if the two intervals overlap. 
* `i1.merge(i2)` where `i1` and `i2` are intervals. Implicitly, constraints to ensure that `i1` and `i2` overlap are added. 

###### Join
Two intervals can be merged, i.e. united. This yields a new interval. The join operation is only defined, if the two intervals overlap. 
* `i1.join(i2)` where `i1` and `i2` are intervals. Implicitly, constraints to ensure that `i1` and `i2` overlap are added.

Note that `merge` and `join` operations can not be nested any further, i.e. something like `i1.merge(i2).join(a.tx)` is not possible.

#### Relations between Intervals
Binary relations between intervals can be stated. They are inspired by the interval relations [defined in SQL](https://dl.acm.org/doi/abs/10.1145/2380776.2380786). 
* `i1.overlaps(i2)`
* `i1.contains(i2)`
* `i1.precedes(i2)`
* `i1.succeeds(i2)`
* `i1.immediatelyPrecedes(i2)`
* `i1.immediatelySucceeds(i2)`
* `i1.equals(i2)`

These relations are syntactic sugar, as they can all be expressed as terms using only from and to selectors.

#### Relations between Intervals and Timestamps 
Additionally, relations between an interval and one or two timestamps are possible. Here, `i` is an interval, `t`, `t1` and `t2` are timestamps: 
* `i.fromTo(t1,t2)`
* `i.between(t1,t2)`
* `t.precedes(i)`
* `t.succeeds(i)`
* `i.contains(t)`

#### asOf 
`asOf` is a special constraint that refers to the transaction interval of a graph element. 
* `a.asOf(t)` is true iff `a.tx_from <= t` and `a.tx_to >= t`, where `a` refers to a graph element 

###### Interval Durations
Durations of intervals can be referred to by simply referring to the interval, e.g. in the context of a duration predicate (see below) `a.tx` would denote the length of `a`'s transaction time.

###### Constant Durations 
Duration constants can be created by the following keywords (`number` is an integer literal):
* `Millis(number)`
* `Seconds(number)`
* `Minutes(number)`
* `Hours(number)`
* `Days(number)`

#### Relations between Durations 
Durations as defined above can be compared: 
* `d1.longerThan(d2)`
* `d1.shorterThan(d2)`
* `d1.lengthAtLeast(d2)`
* `d1.lengthAtMost(d2)`

### Implementation Details 
New temporal `ComparableExpression`s are added.

The processing of all the temporal constraints described above is encapsulated in a `GDLLoaderTemporal.java` that is used by the actual `GDLLoader`.

### CODE REVIEW

**Comment by s1ck** [comment]
This looks interesting. @galpha or @ChrizZz110 are you going to review this?

**Comment by s1ck** [comment]
I would like to do one pass before this is merged. Ideally, after one of you approved the PR.

**Comment by galpha** [comment]
> This looks interesting. @galpha or @ChrizZz110 are you going to review this?

Yes, we'll review this first.

**Comment by ChrizZz110** [comment]
@lc0197 Can you solve the merge conflicts before we start reviewing?

**Comment by lc0197** [comment]
PR now in the dbs-leipzig repo:
https://github.com/dbs-leipzig/gdl/pull/4

**Pull request closed without merging**
